# Generated by Django 5.2.7 on 2026-02-11 17:41

import bajas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=40)),
                ('nivel', models.CharField(max_length=2)),
                ('nuevo_nivel', models.CharField(max_length=2)),
                ('costo_plaza', models.CharField(max_length=100)),
                ('costo_nueva_plaza', models.CharField(max_length=100)),
                ('ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dir', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('NORTE', 'NORTE'), ('SUR', 'SUR'), ('SURESTE', 'SURESTE'), ('ALTIPLANO', 'ALTIPLANO'), ('GAI', 'GAI')], max_length=50)),
                ('tramite', models.CharField(choices=[('LIQUIDACIÓN', 'LIQUIDACIÓN'), ('DESCENSO', 'DESCENSO'), ('JUBILACIÓN', 'JUBILACIÓN'), ('RESCATADO(A)', 'RESCATADO(A)')], max_length=50)),
                ('liquidacion_neta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('RECHAZÓ', 'RECHAZÓ'), ('ACEPTÓ', 'ACEPTÓ'), ('AUSENCIA', 'AUSENCIA'), ('PENDIENTE', 'PENDIENTE'), ('RESCATADO(A)', 'RESCATADO(A)'), ('SIN CONTRATO VIGENTE', 'SIN CONTRATO VIGENTE')], default='RECHAZÓ', max_length=20)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=50, null=True)),
                ('sap', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APLICADO', 'APLICADO')], default='PENDIENTE', max_length=20)),
                ('posicion', models.CharField(blank=True, max_length=20, null=True)),
                ('cambio_plaza', models.CharField(blank=True, max_length=8, null=True)),
                ('antiguedad', models.IntegerField(blank=True, null=True)),
                ('libre', models.BooleanField(default=False)),
                ('confirmacion_descenso', models.BooleanField(default=False)),
                ('observaciones_2', models.CharField(blank=True, max_length=100, null=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(bajas.models.UppercaseMixin, models.Model),
        ),
    ]
