# Generated by Django 5.2.7 on 2026-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='cancelada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='confirmacion_descenso',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='libre',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='sap',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('APLICADO', 'APLICADO')], default='PENDIENTE', max_length=20, null=True),
        ),
    ]
