# Generated by Django 5.2.7 on 2026-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0002_alter_baja_cancelada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='costo_nueva_plaza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='costo_plaza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='nuevo_nivel',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
