# Generated by Django 5.2.7 on 2026-02-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0003_alter_baja_costo_nueva_plaza_alter_baja_costo_plaza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='estatus_baja',
            field=models.CharField(choices=[('REGISTRO', 'REGISTRO'), ('SEGUIMIENTO', 'SEGUIMIENTO'), ('FINALIZACION', 'FINALIZACION'), ('CONCLUIDA', 'CONCLUIDA')], default='REGISTRO', max_length=20),
        ),
    ]
