# Generated by Django 5.2.7 on 2026-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0004_baja_estatus_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baja',
            name='dir',
        ),
        migrations.AddField(
            model_name='baja',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='fuente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='subdireccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
