# Generated by Django 5.2.7 on 2026-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0005_remove_baja_dir_baja_direccion_baja_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='posicion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
