# Generated by Django 5.2.7 on 2026-02-17 17:06

import bajas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0006_alter_baja_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Solicitud', 'Solicitud'), ('Formato de conformidad', 'Formato de conformidad'), ('INE', 'INE'), ('Formato de adeudos', 'Formato de adeudos'), ('Comunicación a GIMP', 'Comunicación a GIMP')], max_length=50)),
                ('archivo', models.FileField(max_length=255, upload_to=bajas.models.generar_ruta_archivo)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='bajas.baja')),
            ],
        ),
    ]
