# Generated by Django 5.2.7 on 2026-02-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0007_documentobaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='grado',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
