# Generated by Django 5.2.7 on 2026-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0008_baja_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='fecha_oficio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='fecha_ultimo_dia_laboral',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='representante_patronal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentobaja',
            name='tipo',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Formato de conformidad y/o Acta Constancia', 'Formato de conformidad y/o Acta Constancia'), ('INE', 'INE'), ('Estimación de cálculo de terminación', 'Estimación de cálculo de terminación'), ('Formato de adeudos', 'Formato de adeudos'), ('Comunicación a GIMP', 'Comunicación a GIMP')], max_length=50),
        ),
    ]
