# Generated by Django 5.2.7 on 2025-11-05 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion_general', models.CharField(max_length=140)),
                ('direccion', models.CharField(choices=[('DIRECCIÓN DE ADMINISTRACIÓN Y SERVICIOS', 'DIRECCIÓN DE ADMINISTRACIÓN Y SERVICIOS'), ('DIRECCIÓN DE COMERCIALIZACIÓN', 'DIRECCIÓN DE COMERCIALIZACIÓN'), ('DIRECCIÓN DE EXPLORACIÓN Y EXTRACCIÓN', 'DIRECCIÓN DE EXPLORACIÓN Y EXTRACCIÓN'), ('DIRECCIÓN DE FINANZAS', 'DIRECCIÓN DE FINANZAS'), ('DIRECCIÓN DE LOGÍSTICA', 'DIRECCIÓN DE LOGÍSTICA'), ('DIRECCIÓN DE PLANEACIÓN, COORDINACIÓN, DESEMPEÑO Y SOSTENIBILIDAD', 'DIRECCIÓN DE PLANEACIÓN, COORDINACIÓN, DESEMPEÑO Y SOSTENIBILIDAD'), ('DIRECCIÓN DE PROCESOS INDUSTRIALES', 'DIRECCIÓN DE PROCESOS INDUSTRIALES'), ('DIRECCIÓN DE TRANSFORMACIÓN ENERGÉTICA', 'DIRECCIÓN DE TRANSFORMACIÓN ENERGÉTICA'), ('DIRECCIÓN GENERAL', 'DIRECCIÓN GENERAL'), ('DIRECCIÓN JURÍDICA', 'DIRECCIÓN JURÍDICA')], max_length=100)),
                ('procedencia', models.CharField(choices=[('Línea de Ética', 'Línea de Ética'), ('Línea de Negocio', 'Línea de Negocio')], max_length=20)),
                ('regimen', models.CharField(choices=[('Confianza', 'Confianza'), ('Sindicalizado', 'Sindicalizado'), ('Ambos', 'Ambos')], max_length=15)),
                ('sindicato', models.CharField(blank=True, choices=[('STPRM', 'STPRM'), ('UNTYPP', 'UNTYPP'), ('Petromex', 'Petromex')], max_length=10, null=True)),
                ('centro', models.CharField(max_length=100)),
                ('area_depto', models.CharField(max_length=100)),
                ('gravedad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('numero_reporte', models.CharField(max_length=50, unique=True)),
                ('fecha_reporte', models.DateField()),
                ('fecha_conocimiento_hechos', models.DateField()),
                ('fecha_prescripcion', models.DateField()),
                ('economica', models.BooleanField(default=False)),
                ('gerencia_responsable', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Sureste', 'Sureste'), ('Altiplano', 'Altiplano'), ('Oficinas Centrales', 'Oficinas Centrales'), ('GAI', 'GAI')], max_length=20)),
                ('lugar', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=140)),
                ('fecha_evento', models.DateField()),
                ('centro_trabajo', models.CharField(max_length=100)),
                ('antecedentes', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(choices=[('contacto', 'Contacto'), ('responsable', 'Responsable')], max_length=15)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='investigaciones.investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigadores', to='investigaciones.investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='Involucrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('antiguedad', models.IntegerField()),
                ('rfc', models.CharField(max_length=20)),
                ('curp', models.CharField(max_length=18)),
                ('direccion', models.CharField(max_length=200)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involucrados', to='investigaciones.investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('subordinacion', models.BooleanField(default=False)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testigos', to='investigaciones.investigacion')),
            ],
        ),
    ]
