# Generated by Django 5.2.7 on 2025-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacionHistorico',
            fields=[
                ('id_investigacion_historico', models.AutoField(db_column='IdInvestigacionHistorico', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('gerencia', models.CharField(db_column='Gerencia', max_length=50)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('ficha', models.CharField(db_column='Ficha', max_length=15)),
                ('regimen_contractual', models.CharField(db_column='RegimenContractual', max_length=2)),
                ('centro_trabajo', models.CharField(db_column='CentroTrabajo', max_length=50)),
                ('motivo_investigacion', models.CharField(db_column='MotivoInvestigacion', max_length=100, null=True)),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=200, null=True)),
                ('sancion_aplicada', models.CharField(db_column='SancionAplicada', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Investigacion_Historico',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='involucrado',
            name='tiene_antecedentes',
            field=models.BooleanField(default=False),
        ),
    ]
