# Generated by Django 5.2.7 on 2025-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0002_investigacionhistorico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='no_constancia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
