# Generated by Django 5.2.7 on 2025-12-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0004_investigacion_montoeconomico_investigacion_sanciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('antiguedad', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportantes', to='investigaciones.investigacion')),
            ],
        ),
    ]
