# Generated by Django 5.2.7 on 2025-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0005_reportante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='observaciones',
            field=models.CharField(max_length=300),
        ),
    ]
