# Generated by Django 5.2.7 on 2025-12-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0006_alter_investigacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='estatus',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Seguimiento', 'Seguimiento'), ('Concluida', 'Concluida')], default='Abierta', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Reporte', 'Reporte para investigación'), ('Citatorio', 'Citatorio'), ('Acta', 'Acta'), ('Dictamen', 'Dictamen'), ('Resultado', 'Resultado de la investigación'), ('Anexo', 'Anexo')], max_length=50)),
                ('archivo', models.FileField(upload_to='investigaciones/documentos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='investigaciones.investigacion')),
            ],
        ),
    ]
