# Generated by Django 5.2.7 on 2025-12-11 21:31

import investigaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0007_investigacion_estatus_documentoinvestigacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='archivo',
            field=models.FileField(upload_to=investigaciones.models.generar_ruta_archivo),
        ),
    ]
