# Generated by Django 5.2.7 on 2025-12-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0008_alter_documentoinvestigacion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='responsable_categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='responsable_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='responsable_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='responsable_ficha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='responsable_puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='gerencia_responsable',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Sureste', 'Sureste'), ('Altiplano', 'Altiplano'), ('GAI', 'GAI')], max_length=20),
        ),
    ]
