# Generated by Django 5.2.7 on 2025-12-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0009_investigacion_responsable_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='estatus',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('SEGUIMIENTO', 'SEGUIMIENTO'), ('CONCLUIDA', 'CONCLUIDA')], default='ABIERTA', max_length=20),
        ),
    ]
