# Generated by Django 5.2.7 on 2025-12-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0010_alter_investigacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(choices=[('CONTACTO', 'CONTACTO'), ('RESPONSABLE', 'RESPONSABLE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='gerencia_responsable',
            field=models.CharField(choices=[('NORTE', 'NORTE'), ('SUR', 'SUR'), ('SURESTE', 'SURESTE'), ('ALTIPLANO', 'ALTIPLANO'), ('GAI', 'GAI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='gravedad',
            field=models.CharField(choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAJA', 'BAJA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='procedencia',
            field=models.CharField(choices=[('ANONIMO', 'ANONIMO'), ('LÍNEA DE NEGOCIO', 'LÍNEA DE NEGOCIO'), ('LÍNEA DE ÉTICA', 'LÍNEA DE ÉTICA'), ('ESCRITO LIBRE INTERNO', 'ESCRITO LIBRE INTERNO'), ('ESCRITO LIBRE EXTERNO', 'ESCRITO LIBRE EXTERNO'), ('CORREO ELECTRONICO', 'CORREO ELECTRONICO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='regimen',
            field=models.CharField(choices=[('CONFIANZA', 'CONFIANZA'), ('SINDICALIZADO', 'SINDICALIZADO'), ('AMBOS', 'AMBOS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='sindicato',
            field=models.CharField(blank=True, choices=[('STPRM', 'STPRM'), ('UNTYPP', 'UNTYPP'), ('PETROMEX', 'PETROMEX')], max_length=10, null=True),
        ),
    ]
