# Generated by Django 5.2.7 on 2025-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0011_alter_contacto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='involucrado',
            name='jornada',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='involucrado',
            name='regimen',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='involucrado',
            name='sindicato',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
