# Generated by Django 5.2.7 on 2025-12-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0012_involucrado_jornada_involucrado_regimen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='involucrado',
            name='seccion_sindical',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='involucrado',
            name='sindicato',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
