# Generated by Django 5.2.7 on 2025-12-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0013_involucrado_seccion_sindical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='estatus',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('SEGUIMIENTO', 'SEGUIMIENTO'), ('ENVIADA_A_CONCLUIR', 'ENVIADA_A_CONCLUIR'), ('CONCLUIDA', 'CONCLUIDA')], default='ABIERTA', max_length=20),
        ),
    ]
