# Generated by Django 5.2.7 on 2025-12-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0014_alter_investigacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='tipo',
            field=models.CharField(choices=[('Reporte', 'Reporte para investigación'), ('Citatorio', 'Citatorio'), ('Acta', 'Acta'), ('Dictamen', 'Dictamen'), ('Resultado', 'Resultado de la investigación'), ('Anexo', 'Anexo'), ('NotificacionConclusion', 'Notificación de Conclusión')], max_length=50),
        ),
    ]
