# Generated by Django 5.2.7 on 2026-01-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0015_alter_documentoinvestigacion_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigacion',
            old_name='sanciones',
            new_name='conductas',
        ),
    ]
