# Generated by Django 5.2.7 on 2026-01-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0016_rename_sanciones_investigacion_conductas'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='ficha_reconsideracion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='reconsideracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='sancion_definitiva',
            field=models.CharField(blank=True, choices=[('SUSPENSION DE LABORES', 'SUSPENSION DE LABORES'), ('SUSTRACCION DE EQUIPO MOBILIARIO', 'SUSTRACCION DE EQUIPO MOBILIARIO'), ('FALTA DE PROBIDAD Y HONRADEZ', 'FALTA DE PROBIDAD Y HONRADEZ'), ('ALTERACION DEL ORDEN', 'ALTERACION DEL ORDEN'), ('PRESENTACION DE DOCUMENTACION IRREGULAR', 'PRESENTACION DE DOCUMENTACION IRREGULAR'), ('ACTITUD INDEBIDA', 'ACTITUD INDEBIDA'), ('FALTAS INJUSTIFICADAS', 'FALTAS INJUSTIFICADAS'), ('NEGLIGENCIA EN EL DESARROLLO DE FUNCIONES', 'NEGLIGENCIA EN EL DESARROLLO DE FUNCIONES'), ('DISCRIMINACION', 'DISCRIMINACION'), ('ACOSO LABORAL O MOBBING', 'ACOSO LABORAL O MOBBING'), ('ACOSO Y/O HOSTIGAMIENTO SEXUAL', 'ACOSO Y/O HOSTIGAMIENTO SEXUAL'), ('CONCURRIR CON EFECTOS DE ESTUPEFACIENTES Y/O EDO DE EBRIEDAD', 'CONCURRIR CON EFECTOS DE ESTUPEFACIENTES Y/O EDO DE EBRIEDAD'), ('INCUMPLIMIENTO DE NORMAS DE TRABAJO Y/O PROCEDIMIENTOS DE TRABAJO', 'INCUMPLIMIENTO DE NORMAS DE TRABAJO Y/O PROCEDIMIENTOS DE TRABAJO'), ('USO INDEBIDO DE UTILES Y/O HERRAMIENTAS DE TRABAJO', 'USO INDEBIDO DE UTILES Y/O HERRAMIENTAS DE TRABAJO'), ('CLAUSULA 253 CCT', 'CLAUSULA 253 CCT'), ('ACTOS DE CORRUPCION', 'ACTOS DE CORRUPCION'), ('MERCADO ILICITO DE COMBUSTIBLES', 'MERCADO ILICITO DE COMBUSTIBLES'), ('OTRAS FALTAS', 'OTRAS FALTAS')], max_length=70, null=True),
        ),
    ]
