# Generated by Django 5.2.7 on 2026-01-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0017_investigacion_ficha_reconsideracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='tipo',
            field=models.CharField(choices=[('Reporte', 'Reporte para investigación'), ('Citatorio', 'Citatorio'), ('Acta', 'Acta'), ('Pruebas', 'Pruebas'), ('Dictamen', 'Dictamen'), ('Resultado', 'Resultado de la investigación'), ('Anexo', 'Anexo'), ('NotificacionConclusion', 'Notificación de Conclusión')], max_length=50),
        ),
    ]
