# Generated by Django 5.2.7 on 2026-01-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0018_alter_documentoinvestigacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='subconducta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
