# Generated by Django 5.2.7 on 2026-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0019_investigacion_subconducta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='conductas',
            field=models.CharField(choices=[('Incumplimiento de normas y procedimientos', 'Incumplimiento de normas y procedimientos'), ('Faltas injustificadas / Abandono de labores', 'Faltas injustificadas / Abandono de labores'), ('Negligencia en el desempeño de funciones', 'Negligencia en el desempeño de funciones'), ('Acoso laboral (mobbing)', 'Acoso laboral (mobbing)'), ('Actitud indebida', 'Actitud indebida'), ('Desobediencia', 'Desobediencia'), ('Alteración del orden y disciplina', 'Alteración del orden y disciplina'), ('Sustracción o robo de bienes', 'Sustracción o robo de bienes'), ('Uso indebido de bienes, herramientas o recursos', 'Uso indebido de bienes, herramientas o recursos'), ('Hostigamiento o acoso sexual', 'Hostigamiento o acoso sexual'), ('Concurrencia en estado inconveniente', 'Concurrencia en estado inconveniente'), ('Divulgación o uso indebido de información', 'Divulgación o uso indebido de información'), ('Ocasionar daños o perjuicios', 'Ocasionar daños o perjuicios'), ('Suspensión unilateral de labores', 'Suspensión unilateral de labores'), ('Discriminación', 'Discriminación'), ('Accidente de trabajo', 'Accidente de trabajo'), ('Otras conductas', 'Otras conductas'), ('Cláusula 253 CCT', 'Cláusula 253 CCT')], default='OTRAS FALTAS', max_length=65),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='sancion_definitiva',
            field=models.CharField(blank=True, choices=[('Incumplimiento de normas y procedimientos', 'Incumplimiento de normas y procedimientos'), ('Faltas injustificadas / Abandono de labores', 'Faltas injustificadas / Abandono de labores'), ('Negligencia en el desempeño de funciones', 'Negligencia en el desempeño de funciones'), ('Acoso laboral (mobbing)', 'Acoso laboral (mobbing)'), ('Actitud indebida', 'Actitud indebida'), ('Desobediencia', 'Desobediencia'), ('Alteración del orden y disciplina', 'Alteración del orden y disciplina'), ('Sustracción o robo de bienes', 'Sustracción o robo de bienes'), ('Uso indebido de bienes, herramientas o recursos', 'Uso indebido de bienes, herramientas o recursos'), ('Hostigamiento o acoso sexual', 'Hostigamiento o acoso sexual'), ('Concurrencia en estado inconveniente', 'Concurrencia en estado inconveniente'), ('Divulgación o uso indebido de información', 'Divulgación o uso indebido de información'), ('Ocasionar daños o perjuicios', 'Ocasionar daños o perjuicios'), ('Suspensión unilateral de labores', 'Suspensión unilateral de labores'), ('Discriminación', 'Discriminación'), ('Accidente de trabajo', 'Accidente de trabajo'), ('Otras conductas', 'Otras conductas'), ('Cláusula 253 CCT', 'Cláusula 253 CCT')], max_length=70, null=True),
        ),
    ]
