# Generated by Django 5.2.7 on 2026-01-14 20:29

import investigaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0021_investigacion_detalles_conducta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('no_constancia', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=(investigaciones.models.UppercaseMixin, models.Model),
        ),
    ]
