# Generated by Django 5.2.7 on 2026-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0022_catalogoinvestigador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involucrado',
            name='seccion_sindical',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='involucrado',
            name='sindicato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
