# Generated by Django 5.2.7 on 2026-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0023_alter_involucrado_seccion_sindical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='procedencia',
            field=models.CharField(choices=[('ANÓNIMO', 'ANÓNIMO'), ('LÍNEA DE NEGOCIO', 'LÍNEA DE NEGOCIO'), ('LÍNEA DE ÉTICA', 'LÍNEA DE ÉTICA'), ('ESCRITO LIBRE INTERNO', 'ESCRITO LIBRE INTERNO'), ('ESCRITO LIBRE EXTERNO', 'ESCRITO LIBRE EXTERNO'), ('CORREO ELECTRÓNICO', 'CORREO ELECTRÓNICO')], max_length=30),
        ),
    ]
