# Generated by Django 5.2.7 on 2026-01-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0024_alter_investigacion_procedencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacion',
            name='subconducta',
        ),
    ]
