# Generated by Django 5.2.7 on 2026-01-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0025_remove_investigacion_subconducta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacion',
            name='area_depto',
        ),
        migrations.RemoveField(
            model_name='investigacion',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='investigacion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='investigacion',
            name='regimen',
        ),
    ]
