# Generated by Django 5.2.7 on 2026-01-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0026_remove_investigacion_area_depto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacion',
            name='descripcion_general',
        ),
    ]
