# Generated by Django 5.2.7 on 2026-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0028_alter_documentoinvestigacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='dias_suspension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='sancion',
            field=models.CharField(blank=True, choices=[('AMONESTACIÓN', 'AMONESTACIÓN'), ('EXHORTO', 'EXHORTO'), ('IMPEDIMENTO (NO ACEPTACIÓN AL SERVICIO)', 'IMPEDIMENTO (NO ACEPTACIÓN AL SERVICIO)'), ('RESPONSABILIDAD ECONÓMICA', 'RESPONSABILIDAD ECONÓMICA'), ('RESCISIÓN DEL CONTRATO', 'RESCISIÓN DEL CONTRATO'), ('SUSPENSIÓN DE LABORES', 'SUSPENSIÓN DE LABORES'), ('SIN RESPONSABILIDAD', 'SIN RESPONSABILIDAD')], max_length=50, null=True),
        ),
    ]
