# Generated by Django 5.2.7 on 2026-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0032_alter_investigacion_conductas'),
    ]

    operations = [
        migrations.AddField(
            model_name='testigo',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testigo',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testigo',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testigo',
            name='ficha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testigo',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testigo',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
