# Generated by Django 5.2.7 on 2026-01-28 17:54

import investigaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0034_alter_documentoinvestigacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='archivo',
            field=models.FileField(max_length=255, upload_to=investigaciones.models.generar_ruta_archivo),
        ),
    ]
