# Generated by Django 5.2.7 on 2026-01-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0036_alter_investigacion_conducta_definitiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacion',
            name='sancion_definitiva',
        ),
    ]
