# Generated by Django 5.2.7 on 2026-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0037_remove_investigacion_sancion_definitiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='tipo',
            field=models.CharField(choices=[('Reporte', 'Reporte para investigación'), ('Citatorio', 'Citatorio'), ('Citatorio_Reportado', 'Citatorio Reportado'), ('Citatorio_Ratificante', 'Citatorio Ratificante'), ('Citatorio_Testigo', 'Citatorio Testigo'), ('Acta', 'Acta'), ('Acta_Comparecencia_Ratificante', 'Acta Comparecencia Ratificante'), ('Acta_Testigo', 'Acta Testigo'), ('Acta_Investigacion', 'Acta de Investigación (Reportados)'), ('Pruebas', 'Pruebas'), ('Dictamen', 'Dictamen'), ('NotificacionConclusion', 'Notificación de Conclusión'), ('Evidencia de medidas preventivas', 'Evidencia de medidas preventivas')], max_length=50),
        ),
    ]
