# Generated by Django 5.2.7 on 2026-01-29 22:04

import investigaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0038_alter_documentoinvestigacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacionSirhn',
            fields=[
                ('ficha', models.CharField(db_column='Ficha', max_length=20, primary_key=True, serialize=False)),
                ('fechainicio', models.CharField(db_column='FechaInicio', max_length=50)),
                ('fechatermino', models.CharField(db_column='FechaTermino', max_length=50)),
                ('motivoinvestigacion', models.CharField(db_column='MotivoInvestigacion', max_length=200)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('sancion', models.CharField(db_column='Sancion', max_length=200)),
            ],
            options={
                'db_table': 'aplicativo_investigaciones',
                'managed': False,
            },
            bases=(investigaciones.models.UppercaseMixin, models.Model),
        ),
    ]
