# Generated by Django 5.2.7 on 2026-01-30 18:21

import investigaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0039_investigacionsirhn'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoinvestigador',
            name='archivo_constancia',
            field=models.FileField(blank=True, null=True, upload_to=investigaciones.models.constancia_upload_path),
        ),
    ]
