# Generated by Django 5.2.7 on 2026-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0040_catalogoinvestigador_archivo_constancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoinvestigador',
            name='archivo_responsiva',
            field=models.FileField(blank=True, null=True, upload_to='responsiva/'),
        ),
    ]
