# Generated by Django 5.2.7 on 2026-01-30 21:28

import investigaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0041_catalogoinvestigador_archivo_responsiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoinvestigador',
            name='archivo_responsiva',
            field=models.FileField(blank=True, null=True, upload_to=investigaciones.models.responsiva_upload_path),
        ),
    ]
