# Generated by Django 5.2.7 on 2026-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0042_alter_catalogoinvestigador_archivo_responsiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacion',
            name='ficha_reconsideracion',
        ),
        migrations.AddField(
            model_name='investigacion',
            name='observaciones_reconsideracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='tipo',
            field=models.CharField(choices=[('Reporte', 'Reporte para investigación'), ('Citatorio', 'Citatorio'), ('Citatorio_Reportado', 'Citatorio Reportado'), ('Citatorio_Ratificante', 'Citatorio Ratificante'), ('Citatorio_Testigo', 'Citatorio Testigo'), ('Acta', 'Acta'), ('Acta_Comparecencia_Ratificante', 'Acta Comparecencia Ratificante'), ('Acta_Testigo', 'Acta Testigo'), ('Acta_Investigacion', 'Acta de Investigación (Reportados)'), ('Pruebas', 'Pruebas'), ('Dictamen', 'Dictamen'), ('Resultado', 'Resultado de la investigación'), ('NotificacionConclusion', 'Notificación de Conclusión'), ('Evidencia de medidas preventivas', 'Evidencia de medidas preventivas'), ('Formato_Reconsideracion', 'Formato de Reconsideración')], max_length=50),
        ),
    ]
