# Generated by Django 5.2.7 on 2026-02-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0043_remove_investigacion_ficha_reconsideracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='involucrado',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportante',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
    ]
