# Generated by Django 5.2.7 on 2026-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0045_alter_involucrado_antiguedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='es_atracción',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='es_coadyugancia',
            field=models.BooleanField(default=False),
        ),
    ]
