# Generated by Django 5.2.7 on 2026-02-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0046_investigacion_es_atracción_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigacion',
            old_name='es_coadyugancia',
            new_name='es_coadyuvancia',
        ),
    ]
