# Generated by Django 5.2.7 on 2026-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0047_rename_es_coadyugancia_investigacion_es_coadyuvancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='es_coadyuvante',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
