# Generated by Django 5.2.7 on 2026-02-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0048_investigador_es_coadyuvante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinvestigacion',
            name='tipo',
            field=models.CharField(choices=[('Reporte', 'Reporte'), ('Citatorio_Reportado', 'Citatorio a persona reportada'), ('Acta_Audiencia_Reportado', 'Acta Audiencia a persona reportada'), ('Dictamen', 'Dictamen'), ('Notificacion_a_reportado', 'Notificación a persona reportada'), ('Evidencia de medidas preventivas', 'Evidencia de medidas preventivas'), ('Convenio de pago', 'Convenio pago'), ('Citatorio', 'Citatorio'), ('Citatorio_Reportante', 'Persona reportante'), ('Citatorio_Testigo', 'Testigo de la persona reportante'), ('Citatorio_Reportado_Testigo', 'Testigo de la persona reportada'), ('Actas', 'Actas Audiencias'), ('Acta_Persona_Reportante', 'Persona reportante'), ('Acta_Testigo', 'Testigo de la persona reportante'), ('Acta_Reportado_Testigo', 'Testigo de la persona reportada'), ('Pruebas', 'Pruebas'), ('Notificacion_LN_Reportante', 'Notificación LN o reportante y aplicación sistema'), ('Resicion_Paraprocesal', 'Resición Paraprocesal'), ('Resicion_Juridico_a_tribunal', 'Resición Jurídico a Tribunal'), ('NotificacionConclusion', 'Notificación de Conclusión'), ('Formato_Reconsideracion', 'Formato de Reconsideración')], max_length=50),
        ),
    ]
