# Generated by Django 5.2.7 on 2026-02-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigaciones', '0049_alter_documentoinvestigacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='sin_elementos',
            field=models.BooleanField(default=False),
        ),
    ]
