# Generated by Django 5.2.7 on 2026-01-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='computer_name',
            field=models.CharField(blank=True, help_text='Nombre de host resuelto por DNS', max_length=255, null=True),
        ),
    ]
