# Generated by Django 5.2.7 on 2026-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_activitylog_computer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('READ', 'Consultar'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('DOWNLOAD', 'Descargar'), ('EXPORT', 'Exportar'), ('SEARCH', 'Búsqueda')], max_length=10),
        ),
    ]
